jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read Unity Version
        id: unityVersion
        run: |
          version=$(grep "m_EditorVersion:" ProjectSettings/ProjectVersion.txt | awk '{print $2}')
          echo "unityVersion=$version" >> $GITHUB_OUTPUT

      - name: Activate Unity
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: ${{ steps.unityVersion.outputs.unityVersion }}
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Build project
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: ${{ steps.unityVersion.outputs.unityVersion }}
          targetPlatform: StandaloneWindows64

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: GameBuild
          path: build
