name: Unity Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Get Unity Version
        id: get-unity-version
        run: |
          version=$(grep "^m_EditorVersion:" ProjectSettings/ProjectVersion.txt | sed 's/m_EditorVersion: //')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Unity - Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ steps.get-unity-version.outputs.version }}
          targetPlatform: WebGL

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-WebGL
          path: build/WebGL