name: Unity Auto Activation Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Activate Unity
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 2022.3.18f1   # 🔹 replace with your ProjectVersion.txt
          customImage: unityci/editor:ubuntu-2022.3.18f1-base-1
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Build project
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.18f1
          customImage: unityci/editor:ubuntu-2022.3.18f1-base-1
          targetPlatform: StandaloneWindows64
          buildName: MyGame
          buildPath: build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyGame-Windows
          path: build
