jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Unity Version
        id: get-unity-version
        run: |
          version=$(grep "^m_EditorVersion:" ProjectSettings/ProjectVersion.txt | sed 's/m_EditorVersion: //')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Unity - Activate
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: ${{ steps.get-unity-version.outputs.version }}
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

      - name: Unity - Build
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: ${{ steps.get-unity-version.outputs.version }}
          targetPlatform: Android
